name: Deploy to Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
      #     chmod 600 ~/.ssh/deploy_key
      #     ssh-keyscan -p ${{ secrets.PROXMOX_PORT }} ${{ secrets.PROXMOX_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to staging
        run: |
          docker build -t procheht-backend ./backend
          docker stop procheht-app || true
          docker rm procheht-app || true
          docker run -d -p 5000:5000 --restart unless-stopped --name procheht-app procheht-backend
